### PR TITLE
add silent mode

### PR DESCRIPTION
**Pull request by phinze**
:wave: Cool little tool you've got here!

I'm trying it out to solve a problem we're seeing over in https://github.com/hashicorp/terraform/pull/901, but I had to add this feature to make it do what we needed.

For now we can point to my fork, but let me know if you're interested in pulling this in. :+1: 

----

support -s flag for silent mode, which continues to process even when a
dependency is not found locally

useful for using deplist to build a list of potentially missing
dependencies suitable for shoving into `go get`.

### CODE REVIEW

**Comment by cespare** [comment]
Interesting. The only problem I have which this is that what you get back depends on what's currently loaded on your machine. If you only depend on one package, but that has 100 transitive dependences, then whether you get 1 or 101 results from deplist depends on whether you have that package available.

I feel like what you actually want is a way to force maxdepth = 1 (maybe `-recursive=false`). Would that cover your needs? I think that is actually the list of things you want to `go get` in terraform.

**Comment by phinze** [comment]
@cespare Thanks for the response! I'm still trying to fully grok the details of how `go get` walks dependencies. Maybe you can help me out.

I thought that "what you get back depends on what's currently loaded on your machine" was necessary in order to properly feed a list of packages into `go get`, but maybe just a top level list is sufficient and `go get` will walk the transitive dependencies properly?

My worry was the case where a direct dependency updates one of _it's_ transitive dependencies. But maybe `go get` handles all that for me?

**Comment by cespare** [comment]
`go get` fetches all transitive dependencies. Typically something like `deplist` isn't required, because you can just do `go get github.com/my/pkg` and it will go out and fetch everything you need.

From glancing at the terraform issue, it seems like you guys are doing something special/fancy with your dependencies.

In any case, I don't see how the list you get with `deplist -s` is useful, because it includes some, but not all, transitive dependencies, depending on what packages are available locally. So I'm pretty sure you either want to fetch all the packages and run `deplist`, or else you only want the first-order dependencies (which we could do with `deplist -recurse=false`).

**Comment by cespare** [comment]
I looked at your Makefile more closely. I understand what's happening now. You basically just want `go get`, except that you don't want to update git in the current repo (but you apparently do want to update all deps to latest). In that case, I think my `-recur=false` suggestion is what you want.

(You should also consider using godep or similar for such a project, to lock dependency versions, so that you get more reproducible builds.)

**Comment by phinze** [comment]
@cespare so our problem was with travis builds was that `go get` was not respecting the branch on which the build was running - forcing travis to check out master every time. that's the thing we're trying to solve. i guess if `go get` resolves transitive dependencies, all i need is `go list | grep -v terraform | go get`. will play with that.

**Comment by cespare** [comment]
`go get` doesn't balk on stdlib packages, so yes, that should work.

**Comment by phinze** [comment]
Cool, after some fiddling, this seems to do what I need:

```
go list ./... | xargs go list -f '{{join .Deps "\n"}}' | sort -u | grep -v github.com/hashicorp/terraform/ | xargs go get -f -u -v
```

Thanks for the help!

**Comment by cespare** [comment]
Glad I could help :)

**Pull request closed without merging**
